"""init schema

Revision ID: b47531c6f9e6
Revises: 
Create Date: 2026-08-25 09:28:13.034296
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'b47531c6f9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('p_succ_delta', sa.Float(), nullable=False),
    sa.Column('value_paise', sa.BigInteger(), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('ev_paise', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_candidates'))
    )
    with op.batch_alter_table('action_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_cand_incident', ['incident_id'], unique=False)

    op.create_table('action_executions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=True),
    sa.Column('candidate_id', sa.String(length=40), nullable=True),
    sa.Column('human_id', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('connector', sa.String(length=30), nullable=False),
    sa.Column('connector_ref', sa.String(length=120), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_executions')),
    sa.UniqueConstraint('idempotency_key', name='uq_exec_idem')
    )
    with op.batch_alter_table('action_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_executions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_exec_incident', ['incident_id'], unique=False)
        batch_op.create_index('ix_exec_state', ['state'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_records',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('actor_role', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=60), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=30), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_records')),
    sa.UniqueConstraint('id', name=op.f('uq_audit_records_id'))
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_audit_org_seq', ['organization_id', 'seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_organization_id'), ['organization_id'], unique=False)

    op.create_table('canonical_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_ref', sa.String(length=200), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('issuer', sa.String(length=60), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('psp', sa.String(length=40), nullable=True),
    sa.Column('gateway', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_events')),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_canon_provider_ext')
    )
    with op.batch_alter_table('canonical_events', schema=None) as batch_op:
        batch_op.create_index('ix_canon_merchant_time', ['merchant_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_canon_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_events_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_events_payment_ref'), ['payment_ref'], unique=False)

    op.create_table('dead_letters',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letters'))
    )
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letters_organization_id'), ['organization_id'], unique=False)

    op.create_table('event_inbox',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=False),
    sa.Column('signature_ok', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_inbox')),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_event_inbox_provider_ext')
    )
    with op.batch_alter_table('event_inbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_inbox_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_event_inbox_status', ['status'], unique=False)

    op.create_table('experiment_assignments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('experiment_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('payment_group_id', sa.String(length=40), nullable=False),
    sa.Column('arm', sa.String(length=12), nullable=False),
    sa.Column('propensity', sa.Float(), nullable=False),
    sa.Column('action_execution_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assignments')),
    sa.UniqueConstraint('experiment_id', 'payment_group_id', name='uq_asgn_exp_group')
    )
    with op.batch_alter_table('experiment_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_assignments_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_assignments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_assignments_payment_group_id'), ['payment_group_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_organization_id'), ['organization_id'], unique=False)

    op.create_table('incident_evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('ref', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_evidence'))
    )
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evid_incident', ['incident_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('human_id', sa.String(length=20), nullable=False),
    sa.Column('sev', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cohort_issuer', sa.String(length=60), nullable=True),
    sa.Column('cohort_method', sa.String(length=40), nullable=True),
    sa.Column('cohort_psp', sa.String(length=40), nullable=True),
    sa.Column('cohort_gateway', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_sr_bp', sa.Integer(), nullable=False),
    sa.Column('current_sr_bp', sa.Integer(), nullable=False),
    sa.Column('rar_paise', sa.BigInteger(), nullable=False),
    sa.Column('rar_lo_paise', sa.BigInteger(), nullable=False),
    sa.Column('rar_hi_paise', sa.BigInteger(), nullable=False),
    sa.Column('affected_payments', sa.Integer(), nullable=False),
    sa.Column('affected_customers', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scenario_ref', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('organization_id', 'human_id', name='uq_incident_org_human')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_merchant_state', ['merchant_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_state'), ['state'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('secret_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('merchant_id', 'provider', name='uq_int_merchant_provider')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_organization_id'), ['organization_id'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_code', sa.String(length=4), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('industry', sa.String(length=40), nullable=False),
    sa.Column('autonomy_mode', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('sr_base_bp', sa.Integer(), nullable=False),
    sa.Column('gmv_mtd_paise', sa.BigInteger(), nullable=False),
    sa.Column('protected_mtd_paise', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_organization_id'), ['organization_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=300), nullable=True),
    sa.Column('feature_version', sa.String(length=30), nullable=False),
    sa.Column('dataset_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('parent_version', sa.String(length=30), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_ver')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_stage'), ['stage'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_topic'), ['topic'], unique=False)
        batch_op.create_index('ix_outbox_undispatched', ['dispatched_at'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('experiment_id', sa.String(length=40), nullable=False),
    sa.Column('assignment_id', sa.String(length=40), nullable=False),
    sa.Column('payment_group_id', sa.String(length=40), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('reward_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes')),
    sa.UniqueConstraint('assignment_id', name='uq_outcome_asgn')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_organization_id'), ['organization_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('payment_ref', sa.String(length=200), nullable=False),
    sa.Column('order_ref', sa.String(length=200), nullable=True),
    sa.Column('customer_ref', sa.String(length=80), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('issuer', sa.String(length=60), nullable=True),
    sa.Column('psp', sa.String(length=40), nullable=True),
    sa.Column('gateway', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_class', sa.String(length=30), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_status_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider', 'payment_ref', name='uq_pay_provider_ref')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_pay_group', ['group_id'], unique=False)
        batch_op.create_index('ix_pay_merchant_time', ['merchant_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_customer_ref'), ['customer_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('human_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('merchant_id', 'human_id', 'version', name='uq_policy_merchant_ver')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_organization_id'), ['organization_id'], unique=False)

    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('action_execution_id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=True),
    sa.Column('policy_version', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('failed_rules', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decisions'))
    )
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_pdec_execution', ['action_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_decisions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_decisions_organization_id'), ['organization_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('feature_version', sa.String(length=30), nullable=False),
    sa.Column('p_success', sa.Float(), nullable=False),
    sa.Column('failure_class', sa.String(length=30), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('features_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_pred_payment', ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_organization_id'), ['organization_id'], unique=False)

    op.create_table('root_cause_candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=False),
    sa.Column('edge_issuer', sa.String(length=60), nullable=True),
    sa.Column('edge_method', sa.String(length=40), nullable=True),
    sa.Column('edge_psp', sa.String(length=40), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('counterfactual_share', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_root_cause_candidates'))
    )
    with op.batch_alter_table('root_cause_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_rcc_incident', ['incident_id'], unique=False)

    op.create_table('sim_scenarios',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cohort_issuer', sa.String(length=60), nullable=True),
    sa.Column('cohort_method', sa.String(length=40), nullable=True),
    sa.Column('cohort_psp', sa.String(length=40), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('true_excess_failures', sa.Integer(), nullable=False),
    sa.Column('true_rar_paise', sa.BigInteger(), nullable=False),
    sa.Column('true_top_cause', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sim_scenarios'))
    )
    with op.batch_alter_table('sim_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sim_scenarios_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sim_scenarios_organization_id'), ['organization_id'], unique=False)

    op.create_table('simulations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=True),
    sa.Column('scenario', sa.String(length=40), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('trials', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('params_hash', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations')),
    sa.UniqueConstraint('incident_id', 'scenario', 'seed', 'params_hash', name='uq_sim_reproducible')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index('ix_sim_merchant', ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))

    op.drop_table('users')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_incident_id'))
        batch_op.drop_index('ix_sim_merchant')

    op.drop_table('simulations')
    with op.batch_alter_table('sim_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sim_scenarios_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sim_scenarios_merchant_id'))

    op.drop_table('sim_scenarios')
    with op.batch_alter_table('root_cause_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_rcc_incident')

    op.drop_table('root_cause_candidates')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_merchant_id'))
        batch_op.drop_index('ix_pred_payment')

    op.drop_table('predictions')
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_decisions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_policy_decisions_merchant_id'))
        batch_op.drop_index('ix_pdec_execution')

    op.drop_table('policy_decisions')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_policies_merchant_id'))

    op.drop_table('policies')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_ref'))
        batch_op.drop_index('ix_pay_merchant_time')
        batch_op.drop_index('ix_pay_group')

    op.drop_table('payments')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_experiment_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_undispatched')
        batch_op.drop_index(batch_op.f('ix_outbox_topic'))
        batch_op.drop_index(batch_op.f('ix_outbox_organization_id'))

    op.drop_table('outbox')
    op.drop_table('organizations')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_stage'))
        batch_op.drop_index(batch_op.f('ix_model_versions_name'))

    op.drop_table('model_versions')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_organization_id'))

    op.drop_table('merchants')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_merchant_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_state'))
        batch_op.drop_index(batch_op.f('ix_incidents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_merchant_id'))
        batch_op.drop_index('ix_incident_merchant_state')

    op.drop_table('incidents')
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evid_incident')

    op.drop_table('incident_evidence')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_merchant_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('experiment_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_assignments_payment_group_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_assignments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_assignments_experiment_id'))

    op.drop_table('experiment_assignments')
    with op.batch_alter_table('event_inbox', schema=None) as batch_op:
        batch_op.drop_index('ix_event_inbox_status')
        batch_op.drop_index(batch_op.f('ix_event_inbox_organization_id'))

    op.drop_table('event_inbox')
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letters_organization_id'))

    op.drop_table('dead_letters')
    with op.batch_alter_table('canonical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_events_payment_ref'))
        batch_op.drop_index(batch_op.f('ix_canonical_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_events_merchant_id'))
        batch_op.drop_index('ix_canon_type')
        batch_op.drop_index('ix_canon_merchant_time')

    op.drop_table('canonical_events')
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_incident_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_action_type'))
        batch_op.drop_index('ix_audit_org_seq')

    op.drop_table('audit_records')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('action_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_exec_state')
        batch_op.drop_index('ix_exec_incident')
        batch_op.drop_index(batch_op.f('ix_action_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_action_executions_merchant_id'))

    op.drop_table('action_executions')
    with op.batch_alter_table('action_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_cand_incident')

    op.drop_table('action_candidates')
    # ### end Alembic commands ###
